site_name: 'Building Detections in Azure'
copyright: '©2023 Ryan Nicholson | Blue Mountain Cyber, LLC'
site_description: 'Building Detections in Azure'
site_author: 'Ryan Nicholson'
extra:
  version: '2023-05-02'

INHERIT: ./base_config.yml

nav:
  - Home: 'index.md'
  - Exercises:
    - 'Exercise 1: Infrastructure Deployment': 'exercises/exercise1.md'
    - 'Exercise 2: Configuring Logging': 'exercises/exercise2.md'
    - 'Exercise 3: True-Positive Event Creation': 'exercises/exercise3.md'
    - 'Exercise 4: Creating the Detection Rule & Automation': 'exercises/exercise4.md'
    - 'Exercise 5: Testing the Detection Rule & Automation': 'exercises/exercise5.md'
    - 'Exercise 6: Tearing Down Resources': 'exercises/exercise6.md'
